services:
  - type: web
    name: meridian-bot-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    healthCheckPath: /healthz
